---
# tasks file for security_tools


- name: Ensure we have reached the security_tools tasks
  debug:
    msg: "Starting security_tools tasks"

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install git, ufw, and openssh-server
  apt:
    name:
      - git
      - ufw
      - openssh-server
      - gnupg
      - gnupg2
    state: present
  become: yes

- name: Ensure UFW is enabled
  ufw:
    state: enabled
    policy: deny
    logging: on
  become: yes

- name: Allow OpenSSH through UFW
  ufw:
    rule: allow
    name: OpenSSH
  become: yes

- name: Ensure .ssh directory exists
  file:
    path: "/home/vagrant/.ssh"
    state: directory
    mode: '0700'

- name: Create ssh key
  command: ssh-keygen -t rsa -b 4096 -N "" -f /home/vagrant/.ssh/id_rsa
  args:
    creates: "/home/vagrant/.ssh/id_rsa"